development:
  adapter: mysql2 # postgresql
  database: rss_email
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2 # postgresql
  database: rss_email_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rss_email
  host: localhost
  pool: 5
  timeout: 5000
